conditions: v1

dist: xenial
language: python
python:
- '3.7'
- '2.7'
- pypy3.5-6.0.0
- '3.6'
- '3.5'
- '3.4'
- pypy2.7-6.0.0

cache:
  pip: true
  directories:
  - $HOME/.cache/pre-commit
  - $HOME/.pre-commit
  - $HOME/Library/Caches/Homebrew

install: (source ./.travis.sh travis:install)

before_script: sudo ldconfig

script: python -m tox.__main__

env:
  global:
    LIBYAML_VERSION: 0.2.2-pre1
    TOXENV: python

jobs:
  fast_finish: true

  .osx: &osx
    if: type IN (api, cron) OR tag IS present
    os: osx
    osx_image: xcode9.4
    language: generic
    before_install: (source ./travis.sh travis:before_install:osx)
    after_failure: cat pyenv-install.log
    before_script: []
    before_cache: brew --cache

  allow_failures:
  - {os: osx, env: {TRAVIS_PYTHON_VERSION: '2.6'}}
  - {os: osx, env: {TRAVIS_PYTHON_VERSION: '2.7'}}
  - {os: osx, env: {TRAVIS_PYTHON_VERSION: pypy3.6-7.0.0}}

  include:
  - python: '2.6'
    dist: trusty
  - {<<: *osx, python: '3.7', env: {TRAVIS_PYTHON_VERSION: '3.7'}}
  - {<<: *osx, python: '2.7', env: {TRAVIS_PYTHON_VERSION: '2.7'}}
  - {<<: *osx, python: pypy3.6-7.0.0, env: {TRAVIS_PYTHON_VERSION: pypy3.6-7.0.0}}
  - {<<: *osx, python: '3.6', env: {TRAVIS_PYTHON_VERSION: '3.6'}}
  - {<<: *osx, python: '3.5', env: {TRAVIS_PYTHON_VERSION: '3.5'}}
  - {<<: *osx, python: '3.4', env: {TRAVIS_PYTHON_VERSION: '3.4'}}
  - {<<: *osx, python: '2.6', env: {TRAVIS_PYTHON_VERSION: '2.6'}}
